from .controller import Controller
from .create_customer import *
from .list_customers import *
from .update_customer import *
from .delete_customer import *
from .create_motorcycle import *
from .list_motorcycles import *
from .update_motorcycle import *
from .delete_motorcycle import *
from .create_order import *
from .list_orders import *
from .delete_order import *